[tidb]
host = "gateway01.ap-southeast-1.prod.aws.tidbcloud.com"
"  # Yahan apna exact TiDB host dalein
port = 4000
user = "2GY8uZidZ9H4ghP.root"                              # Yahan apna username dalein
password = "27XZDvgkkpUBonLI"                          # Yahan apna password dalein
database = "institute_management"                        # Database ka naam